// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.discussion.comment

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoDiscussionCommentNSID = "sh.tangled.repo.discussion.comment"
)

func init() {
	util.RegisterType("sh.tangled.repo.discussion.comment", &RepoDiscussionComment{})
} //
// RECORDTYPE: RepoDiscussionComment
type RepoDiscussionComment struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.discussion.comment" cborgen:"$type,const=sh.tangled.repo.discussion.comment"`
	// body: Comment text
	Body      string `json:"body" cborgen:"body"`
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// discussion: The discussion this comment belongs to
	Discussion string   `json:"discussion" cborgen:"discussion"`
	Mentions   []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References []string `json:"references,omitempty" cborgen:"references,omitempty"`
	// replyTo: If this is a reply, the parent comment's at-uri
	ReplyTo *string `json:"replyTo,omitempty" cborgen:"replyTo,omitempty"`
}
