// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.discussion.state

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoDiscussionStateNSID = "sh.tangled.repo.discussion.state"
)

func init() {
	util.RegisterType("sh.tangled.repo.discussion.state", &RepoDiscussionState{})
} //
// RECORDTYPE: RepoDiscussionState
type RepoDiscussionState struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.discussion.state" cborgen:"$type,const=sh.tangled.repo.discussion.state"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	// discussion: The discussion this state change applies to
	Discussion string `json:"discussion" cborgen:"discussion"`
	// state: The new state of the discussion
	State string `json:"state" cborgen:"state"`
}
