// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.pijul.refUpdate

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	PijulRefUpdateNSID = "sh.tangled.pijul.refUpdate"
)

func init() {
	util.RegisterType("sh.tangled.pijul.refUpdate", &PijulRefUpdate{})
} //
// RECORDTYPE: PijulRefUpdate
type PijulRefUpdate struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.pijul.refUpdate" cborgen:"$type,const=sh.tangled.pijul.refUpdate"`
	// changes: List of change hashes that were applied
	Changes []string `json:"changes" cborgen:"changes"`
	// channel: Channel that was updated
	Channel string `json:"channel" cborgen:"channel"`
	// languages: Map of language name to lines of code
	Languages *PijulRefUpdate_Languages `json:"languages,omitempty" cborgen:"languages,omitempty"`
	// newState: New Merkle hash after update
	NewState string `json:"newState" cborgen:"newState"`
	// oldState: Previous Merkle hash (empty for new channels)
	OldState *string `json:"oldState,omitempty" cborgen:"oldState,omitempty"`
	// repo: Repository identifier
	Repo string `json:"repo" cborgen:"repo"`
}

// Map of language name to lines of code
type PijulRefUpdate_Languages struct {
}
