// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.applyChanges

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoApplyChangesNSID = "sh.tangled.repo.applyChanges"
)

// RepoApplyChanges_Input is the input argument to a sh.tangled.repo.applyChanges call.
type RepoApplyChanges_Input struct {
	// changes: List of change hashes to apply (in order)
	Changes []string `json:"changes" cborgen:"changes"`
	// channel: Target channel to apply changes to
	Channel string `json:"channel" cborgen:"channel"`
	// repo: Repository identifier in format 'did:plc:.../repoName'
	Repo string `json:"repo" cborgen:"repo"`
}

// RepoApplyChanges_Output is the output of a sh.tangled.repo.applyChanges call.
type RepoApplyChanges_Output struct {
	// applied: List of successfully applied change hashes
	Applied []string `json:"applied" cborgen:"applied"`
	// failed: List of changes that failed to apply
	Failed []*RepoApplyChanges_Output_Failed_Elem `json:"failed,omitempty" cborgen:"failed,omitempty"`
}

type RepoApplyChanges_Output_Failed_Elem struct {
	Error string `json:"error" cborgen:"error"`
	Hash  string `json:"hash" cborgen:"hash"`
}

// RepoApplyChanges calls the XRPC method "sh.tangled.repo.applyChanges".
func RepoApplyChanges(ctx context.Context, c util.LexClient, input *RepoApplyChanges_Input) (*RepoApplyChanges_Output, error) {
	var out RepoApplyChanges_Output
	if err := c.LexDo(ctx, util.Procedure, "application/json", "sh.tangled.repo.applyChanges", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
