// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.channelList

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoChannelListNSID = "sh.tangled.repo.channelList"
)

// RepoChannelList_Channel is a "channel" in the sh.tangled.repo.channelList schema.
type RepoChannelList_Channel struct {
	// is_current: Whether this is the currently active channel
	Is_current *bool `json:"is_current,omitempty" cborgen:"is_current,omitempty"`
	// name: Channel name
	Name string `json:"name" cborgen:"name"`
}

// RepoChannelList_Output is the output of a sh.tangled.repo.channelList call.
type RepoChannelList_Output struct {
	Channels []*RepoChannelList_Channel `json:"channels" cborgen:"channels"`
}

// RepoChannelList calls the XRPC method "sh.tangled.repo.channelList".
//
// cursor: Pagination cursor (offset)
// limit: Maximum number of channels to return
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoChannelList(ctx context.Context, c util.LexClient, cursor string, limit int64, repo string) (*RepoChannelList_Output, error) {
	var out RepoChannelList_Output

	params := map[string]interface{}{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.channelList", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
