// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.getDefaultChannel

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoGetDefaultChannelNSID = "sh.tangled.repo.getDefaultChannel"
)

// RepoGetDefaultChannel_Output is the output of a sh.tangled.repo.getDefaultChannel call.
type RepoGetDefaultChannel_Output struct {
	// channel: Default channel name
	Channel string `json:"channel" cborgen:"channel"`
}

// RepoGetDefaultChannel calls the XRPC method "sh.tangled.repo.getDefaultChannel".
//
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoGetDefaultChannel(ctx context.Context, c util.LexClient, repo string) (*RepoGetDefaultChannel_Output, error) {
	var out RepoGetDefaultChannel_Output

	params := map[string]interface{}{}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.getDefaultChannel", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
