// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.changeList

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoChangeListNSID = "sh.tangled.repo.changeList"
)

// RepoChangeList_Author is a "author" in the sh.tangled.repo.changeList schema.
type RepoChangeList_Author struct {
	Email *string `json:"email,omitempty" cborgen:"email,omitempty"`
	Name  string  `json:"name" cborgen:"name"`
}

// RepoChangeList_ChangeEntry is a "changeEntry" in the sh.tangled.repo.changeList schema.
type RepoChangeList_ChangeEntry struct {
	Authors []*RepoChangeList_Author `json:"authors" cborgen:"authors"`
	// dependencies: Hashes of changes this change depends on
	Dependencies []string `json:"dependencies,omitempty" cborgen:"dependencies,omitempty"`
	// hash: Change hash (base32 encoded)
	Hash string `json:"hash" cborgen:"hash"`
	// message: Change description
	Message string `json:"message" cborgen:"message"`
	// timestamp: When the change was recorded
	Timestamp *string `json:"timestamp,omitempty" cborgen:"timestamp,omitempty"`
}

// RepoChangeList_Output is the output of a sh.tangled.repo.changeList call.
type RepoChangeList_Output struct {
	Changes  []*RepoChangeList_ChangeEntry `json:"changes" cborgen:"changes"`
	Channel  *string                       `json:"channel,omitempty" cborgen:"channel,omitempty"`
	Page     int64                         `json:"page" cborgen:"page"`
	Per_page int64                         `json:"per_page" cborgen:"per_page"`
	Total    int64                         `json:"total" cborgen:"total"`
}

// RepoChangeList calls the XRPC method "sh.tangled.repo.changeList".
//
// channel: Pijul channel name (defaults to main channel)
// cursor: Pagination cursor (offset)
// limit: Maximum number of changes to return
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoChangeList(ctx context.Context, c util.LexClient, channel string, cursor string, limit int64, repo string) (*RepoChangeList_Output, error) {
	var out RepoChangeList_Output

	params := map[string]interface{}{}
	if channel != "" {
		params["channel"] = channel
	}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.changeList", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
