// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.changeGet

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoChangeGetNSID = "sh.tangled.repo.changeGet"
)

// RepoChangeGet_Author is a "author" in the sh.tangled.repo.changeGet schema.
type RepoChangeGet_Author struct {
	Email *string `json:"email,omitempty" cborgen:"email,omitempty"`
	Name  string  `json:"name" cborgen:"name"`
}

// RepoChangeGet_Output is the output of a sh.tangled.repo.changeGet call.
type RepoChangeGet_Output struct {
	Authors []*RepoChangeGet_Author `json:"authors" cborgen:"authors"`
	// dependencies: Hashes of changes this change depends on
	Dependencies []string `json:"dependencies,omitempty" cborgen:"dependencies,omitempty"`
	// diff: Raw diff content of the change
	Diff *string `json:"diff,omitempty" cborgen:"diff,omitempty"`
	// hash: Change hash (base32 encoded)
	Hash string `json:"hash" cborgen:"hash"`
	// message: Change description
	Message string `json:"message" cborgen:"message"`
	// timestamp: When the change was recorded
	Timestamp *string `json:"timestamp,omitempty" cborgen:"timestamp,omitempty"`
}

// RepoChangeGet calls the XRPC method "sh.tangled.repo.changeGet".
//
// hash: Change hash to retrieve
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoChangeGet(ctx context.Context, c util.LexClient, hash string, repo string) (*RepoChangeGet_Output, error) {
	var out RepoChangeGet_Output

	params := map[string]interface{}{}
	params["hash"] = hash
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.changeGet", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
