// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.permissions

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoPermissionsNSID = "sh.tangled.repo.permissions"
)

// RepoPermissions_Output is the output of a sh.tangled.repo.permissions call.
type RepoPermissions_Output struct {
	Mask        int64    `json:"mask" cborgen:"mask"`
	Permissions []string `json:"permissions" cborgen:"permissions"`
}

// RepoPermissions calls the XRPC method "sh.tangled.repo.permissions".
//
// repo: Repository identifier in format 'did:plc:.../repoName'
func RepoPermissions(ctx context.Context, c util.LexClient, repo string) (*RepoPermissions_Output, error) {
	var out RepoPermissions_Output

	params := map[string]interface{}{}
	params["repo"] = repo
	if err := c.LexDo(ctx, util.Query, "", "sh.tangled.repo.permissions", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
