// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package tangled

// schema: sh.tangled.repo.discussion

import (
	"github.com/bluesky-social/indigo/lex/util"
)

const (
	RepoDiscussionNSID = "sh.tangled.repo.discussion"
)

func init() {
	util.RegisterType("sh.tangled.repo.discussion", &RepoDiscussion{})
} //
// RECORDTYPE: RepoDiscussion
type RepoDiscussion struct {
	LexiconTypeID string `json:"$type,const=sh.tangled.repo.discussion" cborgen:"$type,const=sh.tangled.repo.discussion"`
	// body: Discussion body/description
	Body       *string  `json:"body,omitempty" cborgen:"body,omitempty"`
	CreatedAt  string   `json:"createdAt" cborgen:"createdAt"`
	Mentions   []string `json:"mentions,omitempty" cborgen:"mentions,omitempty"`
	References []string `json:"references,omitempty" cborgen:"references,omitempty"`
	// repo: The repository this discussion belongs to
	Repo string `json:"repo" cborgen:"repo"`
	// targetChannel: Target Pijul channel for merging patches
	TargetChannel *string `json:"targetChannel,omitempty" cborgen:"targetChannel,omitempty"`
	// title: Discussion title
	Title string `json:"title" cborgen:"title"`
}
