package oauth

var TangledScopes = []string{
	"atproto",

	"repo:sh.tangled.publicKey",
	"repo:sh.tangled.repo",
	"repo:sh.tangled.repo.pull",
	"repo:sh.tangled.repo.pull.comment",
	"repo:sh.tangled.repo.artifact",
	"repo:sh.tangled.repo.issue",
	"repo:sh.tangled.repo.issue.comment",
	"repo:sh.tangled.repo.collaborator",
	"repo:sh.tangled.knot",
	"repo:sh.tangled.knot.member",
	"repo:sh.tangled.spindle",
	"repo:sh.tangled.spindle.member",
	"repo:sh.tangled.graph.follow",
	"repo:sh.tangled.feed.star",
	"repo:sh.tangled.feed.reaction",
	"repo:sh.tangled.label.definition",
	"repo:sh.tangled.label.op",
	"repo:sh.tangled.string",
	"repo:sh.tangled.actor.profile",

	"blob:*/*",

	"rpc:sh.tangled.repo.create?aud=*",
	"rpc:sh.tangled.repo.delete?aud=*",
	"rpc:sh.tangled.repo.merge?aud=*",
	"rpc:sh.tangled.repo.hiddenRef?aud=*",
	"rpc:sh.tangled.repo.deleteBranch?aud=*",
	"rpc:sh.tangled.repo.setDefaultBranch?aud=*",
	"rpc:sh.tangled.repo.forkSync?aud=*",
	"rpc:sh.tangled.repo.forkStatus?aud=*",
	"rpc:sh.tangled.repo.mergeCheck?aud=*",
	"rpc:sh.tangled.pipeline.cancelPipeline?aud=*",
	"rpc:sh.tangled.repo.addSecret?aud=*",
	"rpc:sh.tangled.repo.removeSecret?aud=*",
	"rpc:sh.tangled.repo.listSecrets?aud=*",
}
